version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sho-search-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-wgcgs1f60p2w"
s3_prefix = "sho-search-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["ShoSearch=881829523986.dkr.ecr.ap-northeast-1.amazonaws.com/sho-search"]
